file-server:
  base-uri: 'http://localhost:8167/file/'
  server-path: 'C:\\Users\\iLJiMae\\OneDrive\\Pictures\\file-server\\'

stream:
  image: http://localhost:8167/image/

product:
  openapi:
    base-url: http://localhost:8167